services:

  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "8090:8090"
    expose:
      - "8090" 
    tty: true
  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - "8081:8081"
    expose:
      - "8081"
    tty: true
    
    #restart: always
    #links:
        #- redis
        #- mongo
        #- sql-server
