
FROM golang as builder

#ENV GO111MODULE=on

RUN mkdir /logging

WORKDIR /backend

#COPY go.* ./
COPY go.mod ./
#COPY go.sum ./

RUN go mod download

COPY . .
#COPY ./noSQL ./noSQL

#RUN ls -la

#RUN go get try
#RUN go install

#RUN go get -d -v ./
#RUN go install -v ./

#RUN echo pwd
#RUN go run main.go
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

RUN go build -o /backend/build/myapp

EXPOSE 8090
ENTRYPOINT ["/backend/build/myapp"]